{
 "title": "Locust instant",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "locust_users" }
   ]
  },
  {
   "title": "Fail ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "locust_requests_fail_ratio" }
   ]
  },
  {
   "title": "Max response time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "locust_requests_max_response_time",
     "legendFormat": "{{method}}{{name}}"
    }
   ]
  },
  {
   "title": "Min response time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "locust_requests_min_response_time",
     "legendFormat": "{{method}}{{name}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_requests_avg_response_time",
     "legendFormat": "{{method}}{{name}}"
    }
   ]
  },
  {
   "title": "Current response/second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "locust_requests_current_rps", "legendFormat": "{{method}}{{name}}" }
   ]
  }
 ]
}